---
name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - feature/*
    paths-ignore:
      - '**.md'
jobs:
  Yarn-Lint:
    name: Yarn Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent
